### ISSUE TITLE
No license listed

### ISSUE THREAD

**Issue by CodeCommander** [amgrobelny-box/box-jwt-php#1]
Hi, I'd like to contribute to and use the code for this project but I don't see a license listed for it. Can you clarify what the license is for reuse? If you haven't yet decided, have you considered the [MIT license](https://opensource.org/licenses/MIT)?

**Comment by amgrobelny-box** [comment]
Sorry for the delay! I've added the license. Feel free to fork and roll your own version of this, or submit pull requests for additions and new features you implement. Thanks!

**Comment by CodeCommander** [comment]
Awesome! Thanks.
